casename = "wflow_sbm"
calendar = "proleptic_gregorian"
starttime = "2019-01-01T00:00:00"
endtime = "2019-03-31T00:00:00"
time_units = "days since 1900-01-01 00:00:00"
timestepsecs = 86400

[state]
path_input = "/data/instates.nc"
path_output = "/data/run_default/outstate/outstates.nc"

[input]
path_forcing = "/data/forcings.nc"
path_static = "/data/staticmaps.nc"
gauges = "wflow_gauges"
ldd = "wflow_ldd"
river_location = "wflow_river"
subcatchment = "wflow_subcatch"
forcing = [ "vertical.precipitation", "vertical.temperature", "vertical.potential_evaporation",]
cyclic = [ "vertical.leaf_area_index",]
gauges_grdc = "wflow_gauges_grdc"
gauges_eurac = "wflow_gauges_eurac"

[model]
type = "sbm"
masswasting = true
snow = true
reinit = true
reservoirs = false
lakes = false
glacier = false
kin_wave_iteration = true
kw_river_tstep = 900
kw_land_tstep = 3600
thicknesslayers = [ 100, 300, 800,]
river_routing = "kinematic-wave"
land_routing = "kinematic-wave"

[output]
path = "/data/run_default/output.nc"

[state.vertical]
satwaterdepth = "satwaterdepth"
snow = "snow"
tsoil = "tsoil"
ustorelayerdepth = "ustorelayerdepth"
snowwater = "snowwater"
canopystorage = "canopystorage"

[input.vertical]
altitude = "wflow_dem"
c = "c"
cf_soil = "cf_soil"
cfmax = "Cfmax"
e_r = "EoverR"
f = "f"
infiltcappath = "InfiltCapPath"
infiltcapsoil = "InfiltCapSoil"
kext = "Kext"
"kv₀" = "KsatVer"
leaf_area_index = "LAI"
m = "M_"
maxleakage = "MaxLeakage"
pathfrac = "PathFrac"
potential_evaporation = "pet"
precipitation = "precip"
rootdistpar = "rootdistpar"
rootingdepth = "RootingDepth"
soilminthickness = "SoilMinThickness"
soilthickness = "SoilThickness"
specific_leaf = "Sl"
storage_wood = "Swood"
temperature = "temp"
#tt = "TT"
tt.value=1.3
tti = "TTI"
#ttm = "TTM"
ttm.value=1.3
water_holding_capacity = "WHC"
waterfrac = "WaterFrac"
"θᵣ" = "thetaR"
"θₛ" = "thetaS"

[output.vertical]
zi = "zi"
satwaterdepth = "satwaterdepth"
snow = "snow"
ustorelayerdepth = "ustorelayerdepth"
vwc_percroot = "vwc_percroot"
precipitation = "precip"
actevap = "actevap"
interception = "interception"
potential_evaporation = "potential_evaporation"

[state.lateral.river]
q = "q_river"
h = "h_river"
h_av = "h_av_river"

[state.lateral.subsurface]
ssf = "ssf"

[state.lateral.land]
q = "q_land"
h = "h_land"
h_av = "h_av_land"

[input.lateral.river]
length = "wflow_riverlength"
n = "N_River"
slope = "RiverSlope"
width = "wflow_riverwidth"

[input.lateral.subsurface]
ksathorfrac = "KsatHorFrac"

[input.lateral.land]
n = "N"
slope = "Slope"

[output.lateral.river]
q_av = "q_river"

[output.lateral.land]
q = "q_land"
h = "h_land"


